version: "3"
services:
  mysql_library:
    image: library_atlas:latest
    ports:
      - "3306:3306"
    networks:
      - app_network

  node_api:
    image: riuri/node_api:latest
    env_file:
      - ./.env
    environment:
      PORT: ${PORT}
      MYSQL_HOST: mysql_library
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3001:3000"
    networks:
      - app_network

networks:
  app_network:
